#!/usr/bin/env node

'use strict';

const debug = require('debug')('egg-bin:start-cluster');
const assert = require('assert');
const commander = require('commander');

commander
  .option('--eggPath [eggPath]')
  .option('--baseDir [baseDir]')
  .option('-p, --port [port]')
  .option('--cluster [workers]')
  .option('--sticky')
  .allowUnknownOption(true)
  .parse(process.argv);

const baseDir = commander.baseDir;
const workers = commander.cluster ? Number(commander.cluster) : 1;
const port = commander.port;
const customEgg = commander.eggPath;
const sticky = commander.sticky;

assert(customEgg, 'eggPath required, missing any egg frameworks?');

const options = {
  baseDir,
  workers,
  port,
  customEgg,
  sticky,
};

debug('eggPath:%s options:%j', customEgg, options);

require(customEgg).startCluster(options);
